import { StyleSheet } from "react-native";
import { colors } from "../components/Utils/colors";
export const betslipstyle = StyleSheet.create({
    navtwo:{
        backgroundColor:"#fff",
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"center",
        paddingHorizontal:10,
        paddingVertical:7
     },
     title:{
        fontSize:18,
        fontWeight:"700",
        color:"#2A4747"
     },
     container:{
        flex:1,        
    },
    childone:{
        flex:11,
        paddingHorizontal:5,
        paddingVertical:5,
    },
    childtwo:{
        flex:19,
        backgroundColor:"#fff",
        borderTopLeftRadius:5,
        borderTopRightRadius:5,
        paddingHorizontal:8,
        paddingVertical:5
    },
    box_one:{
        width:"100%",
        backgroundColor:"#fff",
        borderRadius:6,
        paddingHorizontal:10,
        paddingTop:6,
        paddingBottom:6,
        marginTop:2
    },
    box_two:{
        width:"100%",
        backgroundColor:"#f9f9f9",
        borderRadius:10,
        paddingHorizontal:10,
        marginBottom:5,
        paddingBottom:15
    },
    box_three:{
        width:"100%",
        backgroundColor:"#f9F9F9",
        borderRadius:10,
        marginTop:5,
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-between",
        paddingHorizontal:5,
        paddingVertical:2
    },
    text_white:{
        color:"#2A4747",
        fontSize:15,
        marginHorizontal:2,
        fontWeight:"800"
    },
    input_box:{
        width:"73%",
        borderRadius:10,
        marginTop:5,
        borderColor:"#5cb85c",
        borderWidth:1,
        paddingVertical:7,
        paddingHorizontal:10
    },
    bet_btn:{
        width:"25%",
        backgroundColor:"#5cb85c",
        alignItems:"center",
        paddingVertical:10,
        flexDirection:"row",
        justifyContent:"center",
        borderRadius:10,

    },
    progress_box:{
        width:"100%",
        height:"5%",
        backgroundColor:"#E6E6FA",
        borderRadius:50,
        marginTop:2
    },
    lable:{
        width:"100%",
        backgroundColor:"#f9f9f9",
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center",
        borderRadius:5,
        paddingHorizontal:5,
        marginTop:5,
        paddingVertical:8
    },
    balance:{
        fontSize:25,
        fontWeight:"900",
        color:"#2A4747",
        marginVertical:2
    },
    items_text:{
        flexDirection:"row",
        justifyContent:"space-between",
    },
    fs_1:{
        fontSize:15,
        marginVertical:1,
        fontWeight:"700"
    },
    odds:{
        fontSize:15,
        fontWeight:"900",
        marginVertical:1
    },
    box_two_dex:{
        flexDirection:"row",
        justifyContent:"space-between",
        marginTop:13
    },
    text_normal:{
        fontSize:14,
        fontWeight:"800"
     },
    btn_active:{
      width:"33%",
      borderRadius:10,
      flexDirection:"row",
      alignItems:"center",
      justifyContent:"center",
      backgroundColor:"#095256",
      paddingVertical:12
    },
    btn_lable:{
        color:"#fff",
        fontSize:14,
        fontWeight:"800"
   },
    btn_inactive:{
        width:"33%",
        paddingVertical:10,
        borderRadius:10,
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"center",
    },
    lable_incative:{
        color:"#095256",
        fontSize:14,
        fontWeight:"800"
    },
    input_area:{
        flexDirection:"row",
        alignItems:"center",
        justifyContent:"space-between",
    },
    btn_name:{
        fontSize:16,
        fontWeight:"800",
        color:"#fff"
    },
    pot_winings:{
        flexDirection:"row",
        justifyContent:"space-between",
        alignItems:"center"
    },
    progress:{
        height:"100%",
        borderTopLeftRadius:50,
        borderBottomLeftRadius:50,
        backgroundColor:"#5cb85c",
        width:"25%",
        flexDirection:'row',
        alignItems:"center",
        justifyContent:"center"
    },
    progress_lable:{
        position:"relative",
        left:20,
        fontSize:15,
        fontWeight:"700",
        color:"#fff"
    },
    text_range:{
        color:"#2A4747",
        marginTop:5,
        fontWeight:"800",
        fontSize:15
    },
    icon:{
        color:colors.secondary_color
    }
})